FROM fabric8/tomcat-9
RUN  apt-get update && \
     apt-get -y install python3 python3-pip vim && \
     pip3 install flask
COPY *.war /opt/tomcat/webapps/
ENTRYPOINT  FLASK_APP=/opt/app.py flask run --host=0.0.0.0




